### ISSUE TITLE
Civil Protection's suggestion

### ISSUE THREAD

**Issue by CivilProtection123** [MrFrostt/suggestions#11]
If you guys add Scanner units who act like dispatch that would be perfect like we know that some units are unserious or unorganized so if we bring a Whitelist which can punish or reward people on their acts cps will be forced to be more serious. As I know it's an only addon please take it into consideration.

**Comment by MrFrostt** [comment]
Please elaborate your idea further, the idea is unclear to me. Due to the fact that we do have Scanners already.

**Comment by Saxithon** [comment]
He proably meant more active scanners. As you're the only scanner atm.

**Comment by MrFrostt** [comment]
We've got 2 scanners in general tbh, but sure, that will be taken in consideration!
