### ISSUE TITLE
big man drug dealer

### ISSUE THREAD

**Issue by Stalkerinoxd** [MrFrostt/suggestions#12]
[https://steamcommunity.com/sharedfiles/filedetails/?id=1376753131](url)

To be honest, drugs shouldnt be cheap as this and so easy to get. In real life it would be a hassle trying to get a drug, especially heroin or any other. I reccomend atleast rising up the price a little bit and making Heroin hard to get

**Comment by MrFrostt** [comment]
**Thank you for the suggestion, the price will be modified!**
