### ISSUE TITLE
Stalkerino's general suggestion

### ISSUE THREAD

**Issue by Stalkerinoxd** [MrFrostt/suggestions#13]
Staff members, magnificent creatures in their observer habitat ALWAYS, well... not every one of them. I've seen multiple staff members just simply go in observer instead of creating roleplay, from what I have learnt from 4 years of experience is that the staff members are supposed to be the face of the server and create unique and not boring roleplay but I've seen none of that in this community. I reccomend and suggest a stronger enforcement on the observer/noclip command.

**Comment by MrFrostt** [comment]
Solved.
