### ISSUE TITLE
OTA assassin improvements

### ISSUE THREAD

**Issue by katojishifu** [MrFrostt/suggestions#15]
- Increase acrobatic and agility stat to maximum for assassins.
- Remove fall damage, please.
 - Grappling gun pl0x.
- Add OTA voicelines instead of MPF voicelines.

**Comment by MrFrostt** [comment]
1. I can do that manually for every user who is on Assassins.
2. Unfortunately, I can not do that, as it requires coding skills.
3. It's added and can be used already.
4. I can do it, but I will require some help. Because we don't have EP2 mounted, nor it's working correctly.
