### ISSUE TITLE
Remove the roll thing for enslaved vort

### ISSUE THREAD

**Issue by therealabksa** [MrFrostt/suggestions#16]
we will discuss it in the comments.

**Comment by MrFrostt** [comment]
Elaborate further please, so you want to say that enslaved vorts cannot participate in the roll due to their oppression and full slavery?

**Comment by therealabksa** [comment]
Welp i just suggested it on forums it should elaborate further http://www.peacesector.com/forum/m/48346844/viewthread/31909483-vortigaunt-change-list-that-i-want-to-see
