### ISSUE TITLE
A more in-depth social class system

### ISSUE THREAD

**Issue by phalecrocorax** [MrFrostt/suggestions#19]
Everybody's familiar with how HL2RP works - you join the server, make a character and spawn in the city where you roam around and browse various buildings. Beside the city, there's also the nasty restricted zones: the slums/sewers/outlands, where you can go if you want to cement your status as a rebel and live freely without restrictions, at the risk of getting caught.

What you end up getting as a result of this, is people immediately running out of the better part of the city and into the restricted areas which are just plain horrible and nasty in terms of living. You end up with a disproportionate ratio between citizens and rebels, and you get the whole problem of having to make citizenRP appealing.

What if you were to flip that on its head?

What if you instead place every new and old average joe in the slums where crime can run a little rampant compared to the city, and they have to work their way out of the skid-row? They can perhaps save up all their tokens to try and pay the entrance fee into the city, or they could do enough good deeds for the Union and as a perk of loyalism, are granted access to the city. The laws and protocols could be a little more lax in the slums, where punishment is up to the individual civil protection's discretion, and you are treated even more like shit than before.

It'd give more incentive to be a loyalist, so you can actually get out of the shithole that is the slums and will give them a sense of pride and accomplishment; it'd open up more possibilities to citizens since they won't have to be on their best goody-two-shoes behavior and instead have a little more freedom at the cost of protection; it'd add more depth to the MPF who don't have to follow their handbook as strictly anymore and can instead interact with citizens on a more personal level, and it'd also let the lolwebuls get what they want without harming the roleplaying environment - immediately get to the slums.

It's a pretty drastic change and on the current map, it might not work well. But I imagine with a little tweaking and consideration, you could get a pretty sweet system working that benefits every faction.

**Comment by MrFrostt** [comment]
Personally, I love the idea. Hopefully, we can get it to work!
