### ISSUE TITLE
Abska's gathered suggestions 

### ISSUE THREAD

**Issue by therealabksa** [MrFrostt/suggestions#7]
Focus more on rp than scripts.
Give the community a say in the rules.
The rules are to regulated and strict loose them.
Faction rules should be always consulted with the faction leader.
The server is heavily restricted and it should be loosend a bit.
Actually hear the opinion of the opposing party don't ignore them as they always have good and constructive critcism.
Units must respect who are higher than them in ranks because they started to undermine the higher ups and ignore them.
Respect the community rather than calling them "hurtfull groups" those hurtfull groups have poured passion and love to this server and they await change.
The staff must always here the pov of both groups than disrespecting the other group and calling them "hatefull groups".
Remove the gaszones and introduce a better alternative as it turned the citizen population into script whores.

**Comment by MrFrostt** [comment]
Thank you for leaving your suggestion!

**Comment by MrFrostt** [comment]
Correct about 4th
And thank you for elaborating the 5th.

**Comment by therealabksa** [comment]
And about 8 its simply called the oppostion its always there and it should be rather than having yesmen

**Comment by MrFrostt** [comment]
Most of the features are added.
